modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"
issueTrackerURL = "https://github.com/Fallen-Breath/fast-ip-ping/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://github.com/Fallen-Breath/fast-ip-ping"
authors = "Fallen_Breath"
description = '''
Yeet the laggy reversed DNS lookup for pure IP server addresses
'''
logoFile = "icon.png"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "fastipping.mixins.json"
